name: Build Tools
on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  ubuntu_build:
    runs-on: ubuntu-20.04
    name: Ubuntu Tools
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Install Dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -yq --no-install-recommends clang-11 xorg-dev
      
      - name: Configure CMake
        run: |
          cmake -B${{ github.workspace }}/build \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -G"Unix Makefiles"
        env:
          CC: clang-11
          CXX: clang++-11
      
      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build \
                --config ${{ env.BUILD_TYPE }} \
                --target TracyServer \
                -- -j2

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: TracyServerUbuntu
          path: build/TracyServer/TracyServer
    
  osx_build:
    runs-on: macos-10.15 
    name: OSX Tools
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Configure CMake
        run: |
          cmake -B${{ github.workspace }}/build \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -G"Xcode"
      
      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build \
                --config ${{ env.BUILD_TYPE }} \
                --target TracyServer

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: TracyServerOSX
          path: build/TracyServer/Release/TracyServer

  windows_build:
    runs-on: windows-latest
    name: Windows Tools
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build `
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build `
              --config ${{env.BUILD_TYPE}} `
              --target TracyServer `
              -- /m:12

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with: 
        name: TracyServerWin
        path: build/TracyServer/Release/TracyServer.exe
